language: python
sudo: false
cache:
  pip: true
python:
  - "2.7"
  - "3.6"
matrix:
  fast_finish: true
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/python setup.py develop
script:
  - bin/python setup.py test
