[tool.towncrier]
# The package name must be importable for now, even when not used.
# See these pull requests:
# https://github.com/hawkowl/towncrier/pull/107
# https://github.com/hawkowl/towncrier/pull/112
# Workaround can be: package = "towncrier"
package = "zestreleaser.towncrier"
issue_format = "`Issue #{issue} <https://github.com/collective/zestreleaser.towncrier/issues/{issue}>`_"
filename = "CHANGES.rst"
directory = "news/"
title_format = "{version} ({project_date})"
# First underline is used for version/date header.
# Second underline is used for the type names (like 'Bug fixes:').
underlines = ["-", ""]

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking changes:"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "New features:"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug fixes:"
showcontent = true
